$(document).ready(function(){
	$("button").button();
	window.onkeydown=function(event){
		switch(event.keyCode)
		{
			case 65 : $("p").html('a'); 
			break;
			case 66 : $("p").html('b'); 
			break;
			case 67 : $("p").html('c'); 
			break;
			case 68 : $("p").html('d'); 
			break;
			case 69 : $("p").html('e'); 
			break;
			case 70 : $("p").html('f'); 
			break;
			case 71 : $("p").html('g'); 
			break;
			case 72 : $("p").html('g'); 
			break;
			case 73 : $("p").html('i'); 
			break;
			case 74 : $("p").html('j'); 
			break;
			case 75 : $("p").html('k'); 
			break;
			case 76 : $("p").html('l'); 
			break;
			case 77 : $("p").html('m'); 
			break;
			case 78 : $("p").html('n'); 
			break;
			case 79 : $("p").html('o'); 
			break;
			case 80 : $("p").html('p'); 
			break;
			case 81 : $("p").html('q'); 
			break;
			case 82 : $("p").html('r'); 
			break;
			case 83 : $("p").html('s'); 
			break;
			case 84 : $("p").html('t'); 
			break;
			case 85 : $("p").html('u'); 
			break;
			case 86 : $("p").html('v'); 
			break;
			case 87 : $("p").html('w'); 
			break;
			case 88 : $("p").html('x'); 
			break;
			case 89 : $("p").html('y'); 
			break;
			case 90 : $("p").html('z'); 
			break;
			case 20 : $("p").html('Caps Lock'); 
			break;
			case 16 : $("p").html('Shift'); 
			break;
			case 17 : $("p").html('Ctrl'); 
			break;
			case 18 : $("p").html('Alt'); 
			break;
			case 32 : $("p").html('Space'); 
			break;
			case 37 : $("p").html('Left Arrow'); 
			break;
			case 38 : $("p").html('Top Arrow'); 
			break;
			case 39 : $("p").html('Right Arrow'); 
			break;
			case 40 : $("p").html('Buttom Arrow'); 
			break;
			case 13 : $("p").html('Enter'); 
			break;
			case 188 : $("p").html(','); 
			break;
			case 190 : $("p").html('.'); 
			break;
			case 191 : $("p").html('/'); 
			break;
			case 186: $("p").html(';'); 
			break;
			case 222 : $("p").html("{__''__}(ex-'a')"); 
			break;
			case 219: $("p").html('['); 
			break;
			case 221: $("p").html(']'); 
			break;
			case 220: $("p").html('Backslash');
			break;
			case 8: $("p").html('Backspace');
			break;
			case 187: $("p").html('=');
			break;
			case 189: $("p").html('-');
			break;
			case 57: $("p").html('Digit 9');
			break;
			case 56: $("p").html('Digit 8');
			break;
			case 55: $("p").html('Digit 7');
			break;
			case 54: $("p").html('Digit 6');
			break;
			case 53: $("p").html('Digit 5');
			break;
			case 52: $("p").html('Digit 4');
			break;
			case 51: $("p").html('Digit 3');
			break;
			case 50: $("p").html('Digit 2');
			break;
			case 49: $("p").html('Digit 1');
			break;
			case 48: $("p").html('Digit 0');
			break;
			case 192: $("p").html('Backquote ( ` )');
			break;
			case 27: $("p").html('Escape');
			break;
			case 46: $("p").html('Delete');
			break;
			case 33: $("p").html('pg Up');
			break;
			case 34: $("p").html('pg Down');
			break;
			case 35: $("p").html('end');
			break;
			case 36: $("p").html('home');
			break;
			case 96: $("p").html('Numpad 0');
			break;
			case 97: $("p").html('Numpad 1');
			break;
			case 98: $("p").html('Numpad 2');
			break;
			case 99: $("p").html('Numpad 3');
			break;
			case 100: $("p").html('Numpad 4');
			break;
			case 101: $("p").html('Numpad 5');
			break;
			case 102: $("p").html('Numpad 6');
			break;
			case 103: $("p").html('Numpad 7');
			break;
			case 104: $("p").html('Numpad 8');
			break;
			case 105: $("p").html('Numpad 9');
			break;

			case 144: $("p").html('Num lock');
			break;
			case 111: $("p").html('Numpad Divide');
			break;
			case 106: $("p").html('Numpad Multiply');
			break;
			case 109: $("p").html('Numpad Subtract');
			break;
			case 107: $("p").html('Numpad Add');
			break;

			case 45: $("p").html('Insert');
			break;

			case 112: $("p").html('F1');
			break;
			case 113: $("p").html('F2');
			break;
			case 114: $("p").html('F3');
			break;
			case 115: $("p").html('F4');
			break;
			case 116: $("p").html('F5');
			break;
			case 117: $("p").html('F6');
			break;
			case 118: $("p").html('F7');
			break;
			case 119: $("p").html('F8');
			break;
			case 120: $("p").html('F9');
			break;
			case 121: $("p").html('F10');
			break;
			case 122: $("p").html('F11');
			break;
			case 123: $("p").html('F12');
			break;

		}
	}
});